spring:
    application:
        name: pharmacy
    datasource:
        url: jdbc:postgresql://localhost:15001/pharmacy
        username: postgres
        password: secret99
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create

logging:
        level:
            apap.ti.pharmacy2206082764.controller: DEBUG
            web: DEBUG